### ISSUE TITLE
User research

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#1]
We're doing short user interviews with our representatives of CHAI and HOT. @ascalamogna and @awright are already in touch with folks. Let's use this ticket to track questions, conversations and the outcomes. 

cc @hotosm/osma-health

**Comment by awright** [comment]
For reference, we introduced @ascalamogna to the following. User interviews aren't expected (or possible) with everyone.

**Malaria Surveillance & Analytics at Clinton Health Access Initiative (CHAI)**
- Katelyn Woolheater <kwoolheater@clintonhealthaccess.org>
  - Research Associate– 
- Charlotte Dolenz <cDolenz@clintonhealthaccess.org>
  - Global Program Manager
- Arnaud Le Menach <alemenach@clintonhealthaccess.org>
  - Senior Epidemiologist 
- Ayokunle Abogan <AAbogan@clintonhealthaccess.org>

**Others**
- Matt Berg <mberg@ona.io>
  - Co-founder and CEO at Ona Systems Inc
- Chad Blevins <cblevins@usaid.gov>
  - Senior Analyst, USAID
- Caitlin Christman, MPH <cchristman@usaid.gov>
  - Malaria Technical Advisor | President’s Malaria Initiative
- Ashley Thomas <Ashley_Thomas@abtassoc.com>
  - Associate at Abt Associates
- Hugh Sturrock <Hugh.Sturrock@ucsf.edu>
  - Assistant Professor of Epidemiology and Biostatistics 
  - University of California, San Francisco

**Comment by ascalamogna** [comment]
Interview findings can be viewed here: 
https://docs.google.com/document/d/1lXMlA0X0rCAKB6EfjOGJ7L1ozBEQLZWmkDSTCciwsUg/

Detailed interview notes can be viewed here: 
https://docs.google.com/document/d/15sygoBINljom3c54NO8F6BwnZ28OhQY0BQzxeS6YCP0/

**Comment by geohacker** [comment]
Thank you for leading this out @ascalamogna! I'm closing here, but please reopen in case there are any next actions.
