### ISSUE TITLE
Frontend bootstrap checklist

### ISSUE THREAD

**Issue by kamicut** [hotosm/osma-health#11]
- [x] create-react-app
- [x] jeet
- [ ] CI / netlify (or other static providers, any preferences @smit1678 ?)

**Comment by smit1678** [comment]
> jeet

Any particular reason for jeet for the grid? We've been mostly revolving around Bootstrap for many other HOT projects and it would be helpful for cross-project work to be in line. 

> CI / netlify (or other static providers, any preferences @smit1678 ?)

We haven't fully landed on a CI yet but mostly CircleCI at the moment. Deploy to S3 is probably best so we can put behind https.

**Comment by kamicut** [comment]
> netlify
My reasoning behind netlify is that it has [features](https://www.netlify.com/features/) that will speed up development out of the box that we've used in other projects: 

- "Github webhook to deploy" CI 
- preview apps from pull requests
- build logs 
- let's encrypt https 
- single page app push-state URLs (no #).

We can definitely replicate most of these with a combination of CircleCI & S3. If we want non hash-based router URLs we can use Cloudfront. Let's talk about AWS and CircleCI account details on slack.

> jeet
We need a framework to provides a CSS grid system. Because we need something minimal we think bootstrap is bloated for this use case. cc @ascalamogna 

If you have more questions we can jump on a call or talk on slack!

**Comment by smit1678** [comment]
> We can definitely replicate most of these with a combination of CircleCI & S3. If we want non hash-based router URLs we can use Cloudfront. Let's talk about AWS and CircleCI account details on slack.

Great, totally hear you on Netlify but I'd like to limit adding paid services that we can cover with at least AWS. 

> We need a framework to provides a CSS grid system. Because we need something minimal we think bootstrap is bloated for this use case. cc @ascalamogna

Yeah full Bootstrap is too bloated for non-grid stuff and I don't necessarily advocate the use of that in this situation, but are you saying if we just use the Bootstrap grid then it'll be too bloated as well or is there another reason for using Jeet's grid over Bootstrap's grid?

**Comment by ascalamogna** [comment]
@smit1678 I think [jeet](http://jeet.gs/) is easier to use, more flexible, and lighter than bootstrap. I'm personally more familiar with it and since we have a quick deadline, it'll allow us to build faster. I'm not sure exactly what your concerns are besides consistency?

**Comment by smit1678** [comment]
👍 Ok being mindful of consistency here. HOT hasn't set guidelines yet and while we won't have a single framework we revolve around, raised this to understand justification and any impact.
