### ISSUE TITLE
Visual Design

### ISSUE THREAD

**Issue by awright** [hotosm/osma-health#16]
Quick Notes:
- OK to explore outside HOT branding and to align more with the hot analytics tool.

**Comment by ascalamogna** [comment]
@awright @smit1678 I don't think we have resources here to work on a full rebranding. 

Would you be okay with trying to maintain consistency with the analytics tool? This is my recommendation.

Or would you like this to look separate from it? If that's the case, We can do something different, but you might need to restyle it in the future if you develop further HOT umbrella branding that doesn't align with what is developed for the tool. If you choose this option, please provide a couple adjectives that describe the look and feel you're going for.

Any thoughts here? It would be helpful to know in the next day or so what direction to go with.

**Comment by smit1678** [comment]
> I don't think we have resources here to work on a full rebranding.

Agreed and apologies if we miscommunicated that in the meeting. I agree we don't have the time and resources to do a full rebranding at the moment. 

> Would you be okay with trying to maintain consistency with the analytics tool? This is my recommendation.

Yes, this is what I had meant to communicate in the meeting. Let's go with the analytics tool to maintain consistency, but where appropriate make improvements or adjust the style to meet the needs of this tool -- this is what I meant by evolving the analytics style. You make the design decisions to maintain consistency but meet the design needs here.

**Comment by awright** [comment]
I fundamentally agree with @smit1678 here to stay aligned with the Analytics Tool design.  I would though consider reviewing the new design for the HOT site. There might be some inspirations there. 

@smit1678 do you have that link for us to review?

**Comment by ascalamogna** [comment]
great thanks for the input @smit1678 and @awright!

**Comment by geohacker** [comment]
We're making progress here https://github.com/hotosm/osma-health/pull/24
@ascalamogna - can you give a quick update?

**Comment by geohacker** [comment]
This is looking good!
