### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#18]
Started defining the workers in https://github.com/hotosm/osma-health-workers. This is how I imagined the jobs would look like:

1. a job is per country/qa tile set
2. each job does the following:
   1. runs all the workers using run.sh
   2. runs aggregation for this country using boundaries stored in S3.
   3. post results on S3 for the front-end.

The reason why I propose the above is because we get to control the results of each OSMLint function and can guarantee job sequence without worrying about defining dependencies - also easier to test. 

@kamicut - do you think this is a good idea? I think we can also turn each job as worker per country and aggregator per country, just not sure how much overhead would that be in terms of managing the job sequence instead of single contained task for a country.

**Comment by kamicut** [comment]
I think this is fine for now. My initial thoughts were that if there are independent jobs (validators that don't depend on each other's outputs) then it would be easier to scale and debug them independently. We can revisit that type of architecture at a later stage.

**Comment by geohacker** [comment]
Workers and structure has been shipped. https://github.com/hotosm/osma-health-workers/
We'll work on minor modifications this week.
