### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#19]
Per chat with @awright, let's use this ticket to track all the parts that we should document. 

cc @ascalamogna @kamicut

**Comment by geohacker** [comment]
We did a round of overall documentation https://github.com/hotosm/osma-health/blob/master/README.md

**Comment by echeipesh** [comment]
Added `README` that talks about building, running the project and AWS batch container: https://github.com/azavea/hot-osm-population

Added [`README`](https://github.com/azavea/hot-osm-population/blob/de930c3879690efd28200cae71ec9b92e9faf8ce/data/README.md) that talks about generating a training set and talks about data considerations as part of https://github.com/azavea/hot-osm-population/pull/6

**Comment by geohacker** [comment]
Great, thank you @echeipesh!
