### ISSUE TITLE
Infrastructure outline

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#2]
We decided to use [AWS Batch](https://docs.aws.amazon.com/batch/latest/userguide/Batch_GetStarted.html) as a way to easily managed schedule TileReduce jobs. @kamicut and @geohacker are working building an outline. 

3 ER

**Comment by geohacker** [comment]
@kamicut and I pulled together a full cloudformation example of using AWS Batch with spot instances and an osmlint task that pulls qa tiles and pushes results to S3. https://github.com/developmentseed/aws-batch-example

We'll base our current work on this.  The worker will live in osma-health-worker.

**Comment by geohacker** [comment]
To outline why we're diverging from the current OSM Analytics cruncher infrastructure: 

* speed of short-term win - the osm analytics infrastructure takes over 12 hours to run. we want something simpler for immediate wins.
* separation of concerns - reliability of osm-qa-tiles is reduced.
* once osmesa work kicks off should ideally swap qa tiles out for those
* show an example of how context specific analytics projects can live outside of generic osm-analytics

**Comment by awright** [comment]
May I asked a question here? Can you explain (in our totally meeting like 2
minutes away) how and when OSMesa will come into the picture? I am trying
to get a sense of the entire flow and architecture of things.

Thanks!

**Comment by kamicut** [comment]
@smit1678 @awright @moradology here's the outline for the infrastructure. cc @geohacker 
Where would you like to add this for documentation? Let us know what you think!

# OSM Analytics For Health Infrastructure

## Background

OSM Analytics for Health aims to help field-based, academic and governmental organizations to improve their prevention strategies by tracking where the map is incomplete. `hotosm/osma-health` is a web application developed by HOT and Development Seed to assess the quality and accuracy of OpenStreetMap data. 

By combining Worldpop and completely mapped areas in OSM, we can train a model to estimate gaps in building density. We overlay this with other metrics to provide a report of coverage area.

The purpose of this document is to outline the metrics required by the application and the underlying infrastructure that produces them. At a high level our approach involves a periodic generation of vector spatial datasets from primary sources.

## Infrastructure Requirements
- Periodic updating of metrics
- Use of AWS technologies
- Static frontend with minimal API infrastructure
## Data requirements

**Data sources**
Sources of data that will be used to generate the metrics and the map layers


- [**WorldPop**](http://www.worldpop.org.uk/): a raster spatial layer of population counts per 100x100m pixel
- [**OpenStreetMap QA Tiles**](http://osmlab.github.io/osm-qa-tiles): a vector tile dataset containing all OSM data
- **Areas of Interest**: A list of vector geometries for each area where the report is generated

**Derived metrics**
Metrics displayed alongside an area of interest


- **Overall quality indicator**: A qualitative measure of the completeness of the area of interest. 
- **Last time of update:** When was the report last generated?
- **Estimated population**: Population in the area of interest
- **Relative completeness**: A quantitative measure of completeness based on Worldpop and building density
- **Attribute completeness**: A measure of what percentage of missing tags such as ‘residential building’ in OSM building data
- **Recency of edits**: A histogram of how fresh the data in the area of interest is
- **Number of duplicate buildings**: The number of buildings that were mapped multiple times
- **Logical consistency errors**: The number of features that are misaligned or overlapping illogically with other features

**Map layers**

- **Area of interest geometry**: A bounding perimeter around the report area
- **Recency layer**: A spatial gradient layer that displays recency of data
- **Completeness layer**: A spatial category layer that displays relative completeness
## Implementation Overview

Our approach will be two-fold, using a one-time job to generate the “relative completeness” metric and associated tile layer, alongside periodic jobs to generate the other metrics. The output of these jobs is spatial vector data stored in AWS S3, either in GeoJSON or Mapbox Vector Tile format.


![osma-health architecture](https://kamicut-monosnap.s3.amazonaws.com/1._bash_2018-03-28_17-34-09.png)


**One-time ML job**
Azavea is leading the task of building a relative completess metric for a given area of interest. Given WorldPop and the OSM QA tiles, a machine learning training process will generate a model that can fit population counts to OSM building coverage. It will then output geojson for each tile at zoom 12. These tiles will contain:


- Estimated population
- Actual OSM building coverage
- Expected building coverage
- A ratio of projected population to worldpop estimate

The last ratio is the measure of relative completeness. In perfectly mapped areas, it tends to 1, and in poor coverage areas it is less than 1. This 0 to 1 scale can be used for a heatmap layer.

**Periodic batch jobs**
For the other metrics, Development Seed is building an AWS Batch pipeline that takes in WorldPop and the OSM QA tiles and generates vector data. The AWS Batch pipeline is triggered weekly using a scheduled AWS Lambda function. At that time, a job will be scheduled for each country that covers the areas of interest. The underlying cluster for the jobs are spot instances that scale up to meet the demands of the batch then terminate at the end of all jobs in that batch.

The batch jobs will each trigger a series of [OSM Lint](https://github.com/osmlab/osmlint)  and aggregation tasks. The HOT organization has forked the osmlint repository to add additional tasks that suit `osma-health`'s purpose.

## Measuring Success

Our measure for success is that this low maintenance infrastructure allows for `osma-health` to expand beyond the inital metrics.
Additionally, the flexibility of this approach allows for integration with the existing OSM Analytics code. By benchmarking the cost and performance of `osma-health` infrastructure we hope it will be suitable as an underlying batch framework for the metrics in OSM Analytics.

**Comment by awright** [comment]
This is great! (I especially like the isometric implementation overview.)
I'll defer (but also think) about where best to put the doc too. Thanks!

**Comment by geohacker** [comment]
Thank you for outlining this clearly @kamicut!

**Comment by geohacker** [comment]
Moved this to Readme https://github.com/hotosm/osma-health/blob/master/README.md

**Comment by kamicut** [comment]
@geohacker @awright I'd love to somehow keep the "Measuring Success" somewhere so that we don't forget about it. It's what will allow for community adoption of this type of infrastructure 😃
