### ISSUE TITLE
permalink fails to load geojson

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#53]
Looks like going directly to an AOI fails to fetch the geojson and returns: 

![image](https://user-images.githubusercontent.com/371666/39121875-a5313634-4710-11e8-8d8f-2f66e0443032.png)

For example: http://localhost:3000/#/botswana/tsau

**Comment by kamicut** [comment]
@geohacker I can't reproduce this. I tried on multiple browsers with no cache. @ascalamogna could you try to reproduce this?

**Comment by kamicut** [comment]
Actually it seems to be happening only on development hot reload in Chrome. I'll see what the issue is.

**Comment by kamicut** [comment]
It was a race condition. PR incoming.
