### ISSUE TITLE
Final Name for Product

### ISSUE THREAD

**Issue by ascalamogna** [hotosm/osma-health#59]
@awright @smit1678 what is the final name for this product? HOT Analytics for Health?

**Comment by awright** [comment]
To date we have been calling it the "OSM Analytics Health Module" in our contract copy etc but I rather like "HOT Analytics for Health". I would suggest we move with the title you suggest unless @smit1678 recommends otherwise.

**Comment by geohacker** [comment]
Let's go with HOT Analytics for Health.
