### ISSUE TITLE
Duplicate buildings validator

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#8]
I think it might be worth using https://github.com/osmlab/osmlint/tree/master/validators/crossingBuildings - and then check what % of overlap is to identify if both geometries may refer to the same structure.

@kamicut what do you think?

**Comment by kamicut** [comment]
That sounds good. @smit1678 is this how you envision it or do you see it as also identifying buildings that have similar tags?

**Comment by geohacker** [comment]
I think geometries is what we're looking for. Most of the buildings mapped will have the same tags because the remote mapping campaign doesn't get addresses or identifiers for instance.

**Comment by smit1678** [comment]
>  think geometries is what we're looking for. Most of the buildings mapped will have the same tags because the remote mapping campaign doesn't get addresses or identifiers for instance.

👍  focusing on geometries is right. I think there might be a use case in the future to look at addresses or identifiers after field mapping in the future but I think this is harder to solve because of false positives.

**Comment by karitotp** [comment]
@geohacker I did some changes to the crossing buildings validator, mostly it is detecting overlap buildings. I uploaded it to this branch https://github.com/osmlab/osmlint/tree/duplicatedbuilding

**Comment by geohacker** [comment]
@karitotp thank you! can you outline the approach here - are we doing a >90% overlap check? and leave comments in the code? Also let's call this `duplicateBuilding` instead of `duplicatedBuilding`

**Comment by karitotp** [comment]
Yes @geohacker the validator is detecting cases in which the area of one of the building is overlap in more to 90% to another one.
These are some of the detected cases:

![selection_018](https://user-images.githubusercontent.com/11504548/37731532-582aebec-2d10-11e8-88c4-f3227bb53cb4.png)
![selection_019](https://user-images.githubusercontent.com/11504548/37731728-e9f66fa6-2d10-11e8-8280-93ed1f8914b0.png)

> Also let's call this duplicateBuilding instead of duplicatedBuilding

 I [changed](https://github.com/osmlab/osmlint/commit/2cfe2ada012769a0b6e47f467e03a04baa549bd2) the validator name.

**Comment by geohacker** [comment]
@karitotp thank you! we're using HOT's fork of osmlint for this project, so do you mind moving the code to https://github.com/hotosm/osmlint into a branch?
