### ISSUE TITLE
Check total building calculation

### ISSUE THREAD

**Issue by smit1678** [hotosm/osma-health#80]
In the new AOI, https://health.osm-analytics.org/#/botswana/kasane-kazungula, we're currently calculating that there are 52,614 buildings. When downloading buildings via the Export tool with this same AOI, there are currently about 13,247 buildings.

**Comment by geohacker** [comment]
The estimates won't be magnitudes different after we fixed the bug as explained here. https://github.com/hotosm/osma-health/issues/82

There's still fair bit of under estimation on the edges but that's tracked here https://github.com/hotosm/osma-health/issues/79
